add comment seperators

diff --git a/bin/pdfjam-pocketmod b/bin/pdfjam-pocketmod
--- a/bin/pdfjam-pocketmod
+++ b/bin/pdfjam-pocketmod
@@ -1,23 +1,27 @@
 #!/bin/sh
 ##
-##  pdfjam-pocketmod: A shell program to make an 8-page PDF document 
+################################################################################
+##
+##  pdfjam-pocketmod: A shell program to make an 8-page PDF document
 ##  into an 8-up file with pages ordered and oriented for folding as
-##  a pocket-sized booklet, as described at http://repocketmod.com/ 
+##  a pocket-sized booklet, as described at http://repocketmod.com/
 ##
 ##  Author David Firth (http://go.warwick.ac.uk/dfirth)
 ##
 ##  This is a simple wrapper for (three runs of) pdfjam, version N.NN
 ##
 ##
-##  It's hard (?) to set up this particular script to read from /dev/stdin, 
+##  It's hard (?) to set up this particular script to read from /dev/stdin,
 ##  so we'll just insist that the first argument is a file:
+##
+################################################################################
 ##
 E_USAGE=64           ##  for a command line usage error
 for arg
 do
     case $arg in
 	--batch)
-	    printf "pdfjam-pocketmod ERROR: the --batch option is not allowed\n" 1>&2 ; 
+	    printf "pdfjam-pocketmod ERROR: the --batch option is not allowed\n" 1>&2 ;
 	    exit "$E_USAGE" ;;
 	--no-tidy)
 	    n='--no-tidy' ;;
@@ -27,23 +31,27 @@ do
 	    v='--vanilla' ;;
 	--checkfiles)
 	    c='--checkfiles' ;;
-	*) 
+	*)
 	    ;;
     esac
 done
 ##
-sourceFile="$1" ;            
+sourceFile="$1" ;
 shift ;
+##
+################################################################################
 ##
 ##  Some (very) minimal checking of the first argument:
 ##
 if test ! -f "$sourceFile" ;
 then
-    printf "pdfjam-pocketmod ERROR: first argument must be a PDF file\n" ; 
+    printf "pdfjam-pocketmod ERROR: first argument must be a PDF file\n" ;
     exit $E_USAGE ;
 fi
 ##
 ##  That's all the argument checking!
+##
+################################################################################
 ##
 pageSpec="1-8"            ## the default page spec
 case ${1} in
@@ -54,4 +62,6 @@ case ${1} in
 	shift ;;
 esac
 pdfjam $n $q $c $v -o /dev/stdout "$sourceFile" "$pageSpec" | pdfjam --angle 180 $n $q $v -o /dev/stdout /dev/stdin '1,8,7,6' | pdfjam --nup 4x2 --landscape --frame true  "$sourceFile" '2-5' /dev/stdin "$@"
-
+##
+################################################################################
+##
diff --git a/bin/pdfpun b/bin/pdfpun
--- a/bin/pdfpun
+++ b/bin/pdfpun
@@ -1,5 +1,6 @@
 #!/bin/sh
 ##
+################################################################################
 ##  pdfpun: A shell program to n-up pages of a PDF file with
 ##          the n-upped pages ordered from right to left
 ##
@@ -7,6 +8,7 @@
 ##
 ##  This is a simple wrapper for (three runs of) pdfjam, version N.NN
 ##
+################################################################################
 ##
 E_USAGE=64           ##  for a command line usage error
 ##
@@ -14,9 +16,9 @@ for arg
 do
     case $arg in
 	--batch)
-	    printf "pdfpun ERROR: the --batch option is not allowed\n" 1>&2; 
+	    printf "pdfpun ERROR: the --batch option is not allowed\n" 1>&2;
 	    exit "$E_USAGE" ;;
-        --no-tidy) 
+        --no-tidy)
 	    n='--no-tidy' ;;
 	--quiet | -q)
 	    q='-q' ;;
@@ -27,47 +29,46 @@ do
 done
 sourceFile="$1" ;
 shift ;
-##
+################################################################################
 ##  Some (very) minimal checking of the first argument:
 ##
 if test ! -f "$sourceFile" ;
 then
-    printf "pdfpun ERROR: first argument must be a PDF file\n" ; 
+    printf "pdfpun ERROR: first argument must be a PDF file\n" ;
     exit $E_USAGE ;
 fi
 if test "$sourceFile" = /dev/stdin ;
 then
     if tty -s ; then
-	printf "pdfpun ERROR: tty is connected to connected to stdin, no PDF file found\n" 
+	printf "pdfpun ERROR: tty is connected to connected to stdin, no PDF file found\n"
 	exit $E_USAGE ;
     fi
 fi
 ##
 ##  That's all the argument checking!
-##
+################################################################################
 pageSpec="-"         ## the default
 case ${1} in
-    --* | "") 
+    --* | "")
 	;;
     *)     ## a page spec was given
 	pageSpec="$1" ;
 	shift ;;
 esac
-case ${1} in 
+case ${1} in
     --outfile)
 	outFile="$2" ;
         shift; shift ;;
-    *) 
+    *)
 	;;
 esac
-if test -z "$outFile" ; 
-then 
-    printf "pdfpun ERROR: no output file specified\n" 1>&2 ; 
-    exit "$E_USAGE" ;  
-fi 
+if test -z "$outFile" ;
+then
+    printf "pdfpun ERROR: no output file specified\n" 1>&2 ;
+    exit "$E_USAGE" ;
+fi
 pdfjam --reflect true $n $q $c "$sourceFile" "$pageSpec" -o /dev/stdout | \
   pdfjam --landscape --nup 2x1 "$@" -o /dev/stdout | \
     pdfjam --suffix nup --reflect true --fitpaper true $n $q -o "$outFile"
 
-
-
+################################################################################
